# Generated by Django 2.2.4 on 2019-08-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=32)),
                ('job_title', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=64)),
            ],
        ),
    ]
