# Generated by Django 2.2.4 on 2019-08-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('job_title', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobdata',
            name='slug',
            field=models.SlugField(default='test-job'),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='company_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='job_title',
            field=models.CharField(max_length=128),
        ),
    ]
