# Generated by Django 2.2.4 on 2019-08-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190829_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='link',
            field=models.CharField(max_length=256),
        ),
    ]
